version: "3"

vars:
  FUNCTION_APP_NAME: cwa-ws-prod-func-quotes-func

tasks:
  test:
    dir: function
    cmds:
      - go test ./...

  container:build:
    dir: function
    cmds:
      - container system start
      - container build -t clowa/az-func-quote:dev .
    sources:
      - "**/*.go"
    method: checksum

  container:run:
    dir: function
    deps: [container:build]
    cmds:
      - container run -p 8080:8080 clowa/az-func-quote:dev

  compose:up:
    dir: function
    cmds:
      - docker compose up {{.CLI_ARGS}}
    silent: false

  compose:down:
    dir: function
    cmds:
      - docker compose down
    silent: false

  function:build:
    dir: function
    cmds:
      - rm -rf ./bin
      - CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o ./bin/main ./src
    silent: false
    sources:
      - "**/*.go"
    method: checksum

  function:deploy:
    deps: [function:build]
    dir: function
    cmds:
      - func azure functionapp publish {{.FUNCTION_APP_NAME}} --custom
    silent: false
    sources:
      - ./bin/*
      - host.json
      - "**/function.json"
    method: checksum
