version: "3"

tasks:
  build:
    dir: function
    cmds:
      - rm -rf ./bin
      - GOOS="linux" GOARCH="amd64" go build -o ./bin/main ./src/main.go
    silent: false

  run-locally:
    dir: function
    cmds:
      - docker compose up {{.CLI_ARGS}}
    silent: false

  down:
    dir: function
    cmds:
      - docker compose down
    silent: false

  deploy-function:
    deps: [build]
    dir: function
    cmds:
      - func azure functionapp publish cwa-quotes-prod-func --custom
    silent: false

  deploy-infra:
    description: Deploy the current infrastructure code
    dir: terraform
    cmds:
      - terraform init
      - terraform apply

  deploy-all:
    description: Deploy the current code and infrastructure
    tasks:
      - deploy-infra
      - deploy-function
