version: "3"

tasks:
  test:
    dir: function
    cmds:
      - go test ./...

  run-locally:
    dir: function
    cmds:
      - docker compose up {{.CLI_ARGS}}
    silent: false

  down:
    dir: function
    cmds:
      - docker compose down
    silent: false

  build-function:
    dir: function
    cmds:
      - rm -rf ./bin
      - CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o ./bin/main ./src/main.go
    silent: false
    sources:
      - "**/*.go"
    method: checksum

  deploy-function:
    deps: [build-function]
    dir: function
    cmds:
      - func azure functionapp publish cwa-quotes-prod-func --custom
    silent: false
    sources:
      - ./bin/*
    method: checksum

  deploy-infra:
    description: Deploy the current infrastructure code
    dir: terraform
    cmds:
      - terraform init
      - terraform apply

  deploy-all:
    description: Deploy the current code and infrastructure
    deps:
      - deploy-infra
      - deploy-function
